### ISSUE TITLE
equality modulo unique id's 

### ISSUE THREAD

**Issue by tretmans** [TorXakis/TorXakis#422]
for many cases and test cases: we need equality over bexpr modulo unique id's, i.e. neglecting difference in unique id numbers.

**Comment by capitanbatata** [comment]
Let me try to get the requirements straight. This is about equality of behavior expressions (`BExpr`) only, or are there any other structures we want to compare modulo unique id? @CarstenRuetz: are there any other places where unique identifiers will be added, or only at `Ident`?

In the first case I would just define a function

```haskell
(~~) :: BExpr -> BExpr -> Bool
bexp0 ~~ bexp1 = zero (bexp0) == zero (bexp1)
```

where `zero` takes a behavior expression and set all the unique identifiers to zero. My guess is that due to lazy evaluation only one traversal will be needed. I can benchmark this against the standard equality between `BExpr` (`==`), if only one traversal is done we should see only one constant increment in the execution time.

If there is a performance penalty the question is whether we want to sacrifice a simple design in favor of more performance. This depends on how often such a `~~` operator would be needed.

**Comment by capitanbatata** [comment]
@CarstenRuetz for a more dynamic discussion it'd be nice if you could join our [gitter channel](https://gitter.im/TorXakis/Lobby).

**Comment by CarstenRuetz** [comment]
@capitanbatata To keep it in one place, I'll keep it here for now

Requirement is to determine the equality of two ProcDefs modulo unids.
There is indeed the BExpr, but also (again) ChanId and VarId at the ProcDefs level.

Performance-wise I don't mind: there will be a couple of tests but it's not executed on the fly during test generation. 
@tretmans Do you need it for s.th. else than tests of TorXakis itself? Does performance play a role?

**Comment by capitanbatata** [comment]
Ok, so if @tretmans does not have any objections I can implement in the way I described above.
