### ISSUE TITLE
Use defined function for VExpr variable substitution

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#425]
See \sys\behave\src\Subst.hs

Get the FuncDefs from the MONAD instead of using Map.empty
Optimization is possible.

```
instance Subst VExpr
  where
    subst x = TxsDefs.subst x (Map.empty :: Map.Map FuncId (FuncDef VarId))    
```

**Comment by pjljvandelaar** [comment]
Use the defined functions in the var by value substation of Behaviour Expressions.
In Subst.hs change `subst :: TxsDefs.VEnv -> e -> e` into `subst :: TxsDefs.VEnv -> Map.Map FuncId (FuncDef VarId) -> e -> e`

Furthermore, like in ValExprImpls.hs (line 414 & 445 currently outcommented this this issue is solved)
check for empty mapping, since then nothing has to be substituted.

Note: comment of subst and compSubst is incorrect: should be `Substitute variables by value expression in value expression ....` since it is not mandatory to provide a value (as is already indicated by `change variable kind` in compSubst.

**Comment by pjljvandelaar** [comment]
related to #133
