### ISSUE TITLE
Semantics of HIDE and exit sorts

### ISSUE THREAD

**Issue by dnadales** [TorXakis/TorXakis#670]
The exit sorts of a `HIDE` expression are the same as the exit sorts of the subexpression:

```haskell
              | HIDE FormalChannels IN BehaviourExpr1 EndIn
                {  $2.inhNodeUid   = $$.inhNodeUid + 1
                ;  $4.inhNodeUid   = $2.synMaxUid + 1
                ;  $$.synMaxUid    = $4.synMaxUid
                ;  $2.inhSigs      = $$.inhSigs
                ;  $4.inhSigs      = $$.inhSigs
                ;  $4.inhChanSigs  = map (\(IdChan c) -> c ) $ scopeMerge (map IdChan $$.inhChanSigs) (map IdChan $2)
                ;  $4.inhVarSigs   = $$.inhVarSigs
                ;  $$.synExitSorts = $4.synExitSorts
                ;  $$ = hide $2 $4
                }
```

Shouldn't the formal channels be hidden from the exit sorts?

**Comment by pjljvandelaar** [comment]
Exit Sorts are the type of the `arguments` over the EXIT channel.
The exit sorts of a hide are indeed equal to the exit sort of the Behaviour Expression in which some channels are hidden.
The exit sorts are unrelated to the hidden channels.

Just to give an example
```
HIDE [ myChannel :: Int ] IN
       A ? x >-> B ? y >-> myChannel ! x+y >-> EXIT ! "hello" ! 2*x + y
     |[ myChannel ]|
       C? z >-> myChannel ? sum >-> EXIT ?s ! sum+z
NI
```
will only exit with both "hello" and 2*x+y when z == x, otherwise the process changes in `STOP`

**Comment by dnadales** [comment]
Clear. Thanks.
